### ISSUE TITLE
Inline annotations in files with spell-check issues

### ISSUE THREAD

**Issue by spier** [reitermarkus/aspell#1]
hi @reitermarkus and thanks for this nice Action.

I am new to [aspell](http://aspell.net/) but I am using a couple of other GitHub Actions already in https://github.com/InnerSourceCommons/InnerSourcePatterns.

I already got your Action to run in this experiment, so far so good :)
https://github.com/InnerSourceCommons/InnerSourcePatterns/pull/272

Right now the output of aspell is only available in the logs.

I am wondering if it would be possible to create inline annotations in files that have spell-check issues?
That way it would be easier for PR authors to spot where the issue is and fix it.

Any pointers would be appreciated.

**Comment by reitermarkus** [comment]
The annotations should already show up in the Files tab in pull requests, don't they?

**Comment by spier** [comment]
You are right, it already works. 
Not sure where I was looking the last time.

Now I see inline annotations like this:
![Screen Shot 2021-01-09 at 17 03 21 ](https://user-images.githubusercontent.com/163029/104098269-c6494b00-529c-11eb-9cab-822e2a0f4107.JPG)

Will close the issue.

**Comment by spier** [comment]
One other related question if I may:
In the meantime I found this other action [rojopolis/spellcheck-github-actions](https://github.com/rojopolis/spellcheck-github-actions) which is a wrapper around `PySpelling`, which in turn uses `aspell` as I understand.

Was just curious if you have seen that other action and what you think about the pros/cons of the `PySpelling` wrapper when compared to using `aspell` directly? Not saying that one is better than the other, just interested in learning more about the use cases for both of them as this is my first time trying to automate any sort of spell-checking.

**Comment by reitermarkus** [comment]
No, I haven't seen `PySpelling` or the other action before, so I can't comment on which use cases they might be used for.

**Comment by spier** [comment]
Ok. No problem and thanks for the quick responses.
I already learned a bit more about spell checking today at least :)
